FileName = 'dig.xlsx';
digData = rmmissing(readtable(FileName));
[nData, nFeatures] = size(digData);

tree1 = fitrtree(digData(:, {'TRTMT','AGE','RACE','SEX','EJF_PER','EJFMETH','BMI','KLEVEL','CREAT',...
                'DIGDOSER','CHFDUR','RALES','ELEVJVP','PEDEMA','RESTDYS','EXERTDYS','ACTLIMIT',...
                'S3','PULCONG','NSYM','HEARTRTE','DIABP','SYSBP','CHFETIOL','PREVMI','ANGINA',...
                'DIABETES','HYPERTEN','DIGUSE','KSUPP','ACEINHIB','NITRATES','HYDRAL','VASOD','DIGDOSE'}),...
                digData.DWHFDAYS, 'MaxNumSplits', 3);
view(tree1,'Mode','graph')
tree2 = fitrtree(digData(:, {'TRTMT','AGE','RACE','SEX','EJFMETH','BMI','KLEVEL','CREAT',...
                'DIGDOSER','CHFDUR','RALES','ELEVJVP','PEDEMA','RESTDYS','EXERTDYS','ACTLIMIT',...
                'S3','PULCONG','NSYM','HEARTRTE','DIABP','SYSBP','CHFETIOL','PREVMI','ANGINA',...
                'DIABETES','HYPERTEN','DIGUSE','KSUPP','ACEINHIB','NITRATES','HYDRAL','VASOD','DIGDOSE'}),...
                digData.DWHFDAYS, 'MaxNumSplits', 9);
view(tree2,'Mode','graph')
tree3 = fitrtree(digData(:, {'TRTMT','AGE','RACE','SEX','BMI','KLEVEL','CREAT',...
                'DIGDOSER','CHFDUR','NHOSP'}), digData.DWHFDAYS, 'MaxNumSplits', 5);
view(tree3,'Mode','graph')